const lang_obj = {
    tr: {
        privacy: 'Gizlilik Politikası',
        no_data: 'Veri Toplanmaz',
        app: 'Uygulama:',
        overview: 'Genel Bakış',
        the_app: '“Uygulama',
        by: '',
        cost: 'tarafından ücretsiz olarak sunulmaktadır ve olduğu gibi kullanılmak üzere tasarlanmıştır',
        developer: 'Geliştirici:',
        your_privacy: 'Gizliliğinize saygı duyuyoruz. Bu Uygulama herhangi bir kişisel veya cihaz verisini',
        collect: 'toplamaz, saklamaz veya paylaşmaz.',
        any: '',
        accounts: 'Uygulamada hesap, analiz, reklam SDK’sı, izleyici veya çerez gibi takip araçları yoktur',
        collection: 'Bilgi Toplama ve Kullanımı',
        request: 'Uygulama, cihazınızda yerel olarak çalışması için gerekli olanların ötesinde hiçbir bilgi talep etmez, erişmez, toplamaz veya işlemez. Seçtiğiniz ayarlar ve tercihler cihazınızda kalır ve bize gönderilmez.',
        data: 'Veri Paylaşımı',
        share: 'Veri toplanmadığı için herhangi bir üçüncü taraf, hizmet sağlayıcı, reklamcı, bağlı ortaklık veya analiz platformu ile veri paylaşımı yapılmaz.',
        cookies: 'Çerez ve Takip',
        tracking: 'Uygulama çerez veya benzeri takip teknolojileri kullanmaz.',
        children: 'Çocukların Gizliliği',
        suitable: 'Uygulama her yaş grubuna uygundur. 13 yaş altındaki çocuklardan veya başka herhangi bir kullanıcıdan bilerek kişisel bilgi toplanmaz.',
        security: 'Güvenlik',
        secure: 'Uygulama kullanıcı verisi işlemediği için sunucularımızda korunması gereken kişisel veri bulunmamaktadır. Uygulamanın orijinal ve güvenli sürümünü edinmek için yalnızca resmi uygulama mağazalarından indirmenizi öneririz.',
        changes: 'Politikadaki Değişiklikler',
        update: 'Uygulama veri toplamaya başlamaya karar verirse, bu politika değişiklikler yürürlüğe girmeden önce güncellenecektir.',
        last: 'Son güncelleme',
        date: 'tarihi yenilenecek ve gerektiğinde uygulama içinde ya da uygulama mağazası ilanında bildirim sağlanacaktır',
        contact: 'İletişim',
        about: 'Bu Gizlilik Politikası veya uygulamanın gizlilik uygulamaları hakkında sorularınız varsa:',
        web: 'Web site:',
        effective: 'Yürürlük',
        june: 'Haziran',
        august: 'Ağustos',
        rights: 'Tüm hakları saklıdır'
    },
    en: {
        privacy: 'Privacy Policy',
        no_data: 'No Data Collected',
        app: 'App:',
        overview: 'Overview',
        the_app: 'the “App',
        by: 'is provided by',
        cost: 'at no cost and is intended to be used as is',
        developer: 'Developer:',
        your_privacy: 'We respect your privacy. This App does',
        collect: 'not collect, store, or share',
        any: 'any personal or device data.',
        accounts: 'There are no accounts, analytics, advertising SDKs, trackers, or cookies',
        collection: 'Information Collection and Use',
        request: 'The App does not request, access, collect, or process any information about you or your device beyond what is necessary for the App to function locally on your device. Any settings or preferences you choose remain on your device and are not transmitted to us.',
        data: 'Data Sharing',
        share: 'Because we do not collect data, we do not share any data with third parties, service providers, advertisers, affiliates, or analytics platforms.',
        cookies: 'Cookies and Tracking',
        tracking: 'The App does not use cookies or similar tracking technologies.',
        children: 'Children’s Privacy',
        suitable: 'The App is suitable for users of all ages. We do not knowingly collect personal information from children under 13, or from any user.',
        security: 'Security',
        secure: 'Since the App does not handle user data, there is no personal information stored on our servers that requires protection. To ensure authenticity and integrity, download the App only from official app stores where we publish it.',
        changes: 'Changes to This Policy',
        update: 'If the App changes to begin collecting data, this policy will be updated before such changes take effect. We will revise the',
        last: 'Last updated',
        date: 'date below and, where required, provide notice within the App or via the app store listing',
        contact: 'Contact Us',
        about: 'If you have questions about this Privacy Policy or the App’s practices, contact:',
        web: 'Website:',
        effective: 'Effective',
        june: 'June',
        august: 'August',
        rights: 'All rights reserved'
    }
};