const lang_obj = {
    tr: {
        score: 'Skor',
        rows: 'Satir',
        level: 'Seviye',
        start_game: 'Basla',
        reset_game: 'Sifirla',
        game_over: 'Oyun Bitti',
        high_score: 'En Yuksek Skor',
        max_rows: 'Maks. Satir',
        pause_game: 'Duraklat',
        resume_game: 'Devam Et',
        nav_home: 'Anasayfa',
        projects: 'Projeler',
        lcd: 'LCD Karakter Hesaplayici',
        nav_movies: 'Filmler',
        face_detector: 'Yuz Taniyici',
        games: 'Oyunlar',
        pong: 'Pin Pon',
        xox: 'XOX',
        resume: 'Ozgecmis',
        settings: 'Ayarlar',
        turkish: 'Turkce'
    },
    en: {
        score: 'Score',
        rows: 'Rows',
        level: 'Level',
        start_game: 'Start',
        reset_game: 'Reset',
        game_over: 'Game Over',
        high_score: 'High Score',
        max_rows: 'Max Rows',
        pause_game: 'Pause',
        resume_game: 'Resume',
        nav_home: 'Home',
        projects: 'Projects',
        lcd: 'LCD Character Generator',
        nav_movies: 'Movies',
        face_detector: 'Face Detector',
        games: 'Games',
        pong: 'Ping Pong',
        xox: 'Tic Tac Toe',
        resume: 'Resume',
        settings: 'Settings',
        turkish: 'Turkce'
    }
};