const langObj = {
    'tr': {
        'turkey': 'Türkiye',
        'skills': 'YETENEKLER',
        'software_development': 'Yazılım Geliştirme',
        'interests': 'İLGİ ALANLARI',
        'mobile_development': 'Mobil Programlama',
        'machine_learning': 'Makine Öğrenmesi',
        'image_processing': 'Görüntü İşleme',
        'autonomous_system': 'Otonom Sistemler',
        'game_development': 'Oyun Geliştirme',
        'languages': 'DİLLER',
        'english': 'İngilizce',
        'pwp': 'Profesyonel çalışma yetkinliği',
        'turkish': 'Türkçe',
        'nbp': 'Yerli veya ikinci dil yetkinliği',
        'software_developer': 'Yazılım Geliştirici',
        'prsnl_desc': 'The best adjective that describes me is curious. I always want to learn new things and search them to discover.',
        'education': 'EĞİTİM',
        'computer_engineering': 'Bilgisayar Mühendisliği',
        'comu': 'Çanakkale Onsekiz Mart Üniversitesi',
        'gpa': 'GNO',
        'courses': 'Dersler',
        'read_more': 'daha fazla',
        'read_less': 'daha az',
        'management_i_s': 'Yönetim Bilişim Sistemleri',
        'anatolian_university': 'Anadolu Üniversitesi',
        'present': 'Devam Ediyor',
        'work_experience': 'İŞ DENEYİMİ',
        'technical_support': 'Teknik Destek',
        'ts_desc': 'Uzaktan Eğitim Merkezi, Çanakkale Onsekiz Mart Üniversitesi bünyesinde kısmi zamanlı çalışan öğrenci.',
        'ce_intern': 'Bilgisayar Mühendisliği Stajı',
        'inc': 'A.Ş.',
        'cei_desc': 'Eğitim teknolojileri, uygulama ve oyun geliştirme alanında staj.',
        'achievements': 'Başarılar',
        'tasks': 'Görevler',
        'cashier': 'Kasiyer',
        'sales_consultant': 'Satış Danışmanı',
        'certificates': 'SERTİFİKALAR',
        'see_credential': 'Sertifikayı gör',
        'final_project': 'Final Projesi',
        'project': 'Proje'
    },
    'en': {
        'turkey': 'Turkey',
        'skills': 'SKILLS',
        'software_development': 'Software Development',
        'interests': 'INTERESTS',
        'mobile_development': 'Mobile Development',
        'machine_learning': 'Machine Learning',
        'image_processing': 'Image Processing',
        'autonomous_system': 'Autonomous Systems',
        'game_development': 'Game Development',
        'languages': 'LANGUAGES',
        'english': 'English',
        'pwp': 'Professional Working Proficiency',
        'turkish': 'Turkish',
        'nbp': 'Native or Bilingual Proficiency',
        'software_developer': 'Software Developer',
        'prsnl_desc': 'The best adjective that describes me is curious. I always want to learn new things and search them to discover.',
        'education': 'EDUCATION',
        'computer_engineering': 'Computer Engineering',
        'comu': 'Canakkale 18th March University',
        'gpa': 'GPA',
        'courses': 'Courses',
        'read_more': 'read more',
        'read_less': 'read less',
        'management_i_s': 'Management Information Systems',
        'anatolian_university': 'Anadolu University',
        'present': 'Present',
        'work_experience': 'WORK EXPERIENCE',
        'technical_support': 'Technical Support',
        'ts_desc': 'Part-time working student at Canakkale 18th March University Distance Education Center.',
        'ce_intern': 'Computer Engineering Internship',
        'inc': 'Inc.',
        'cei_desc': 'Educational technologies, application and game development.',
        'achievements': 'Achievements',
        'tasks': 'Tasks',
        'cashier': 'Cashier',
        'sales_consultant': 'Sales Consultant',
        'certificates': 'CERTIFICATES',
        'see_credential': 'See credential',
        'final_project': 'Final Project',
        'project': 'Project'
    }  
};