const lang_obj = {
    tr: {
        turkiye: 'Türkiye',
        skills: 'YETENEKLER',
        software_development: 'Yazılım Geliştirme',
        interests: 'İLGİ ALANLARI',
        fullstack_development: 'Full Stack Geliştirme',
        embedded_software: 'Gömülü Yazılımlar',
        mobile_development: 'Mobil Programlama',
        machine_learning: 'Makine Öğrenmesi',
        image_processing: 'Görüntü İşleme',
        autonomous_system: 'Otonom Sistemler',
        game_development: 'Oyun Geliştirme',
        languages: 'DİLLER',
        english: 'İngilizce',
        pwp: 'Profesyonel çalışma yetkinliği',
        turkish: 'Türkçe',
        nbp: 'Yerli veya ikinci dil yetkinliği',
        software_developer: 'Yazılım Geliştirici',
        prsnl_desc: 'Beni en iyi tanımlayan sıfat meraktır. Yeni teknolojiler keşfetmek ve öğrenmek için sık sık araştırma yapmaktan keyif alırım.',
        education: 'EĞİTİM',
        computer_engineering: 'Bilgisayar Mühendisliği',
        comu: 'Çanakkale Onsekiz Mart Üniversitesi',
        gpa: 'GNO',
        courses: 'Dersler',
        read_more: 'daha fazla',
        read_less: 'daha az',
        less_courses: 'Mobil Programlama, Görüntü İşleme, Bilgisayar Ağları, Nesneye Dayalı Analiz ve Tasarım',
        more_courses: ', Algoritma ve Programlama, Lineer Cebir, Yapısal Programlama, Veri Yapıları, Nesneye Yönelik Programlama, Ayrık Matematik, Diferansiyel Denklemler, Analog Elektronik, Olasılık ve İstatistik, Sayısal Yöntemler, Web Tasarımı ve Programlama, Bilgisayar Organizasyonu, Sayısal Elektronik, Veri Tabanı Yönetim Sistemleri, İşletim Sistemleri, Veri Yönetimi ve Dosya Yapıları, Windows Programlama, Mikro Denetleyiciler, Veri Madenciliği, Programlama Dilleri Kavramları, Veri Haberleşmesi, Programlanabilir Denetleyiciler, Mikroişlemciler ve Mikrobilgisayar, Yazılım Mühendisliği, Formal Diller ve Otomat Teorisi, Bulut Bilişime Giriş, Bilgisayar Mimarisi, Algoritma Analizi, Gömülü Sistem Tasarımı, Nesnelerin İnternetine Giriş, Yazılım Sınama Teknikleri',
        uavproject: 'İnsansız Hava Aracı Projesi',
        management_i_s: 'Yönetim Bilişim Sistemleri',
        anatolian_university: 'Anadolu Üniversitesi',
        present: 'Devam Ediyor',
        work_experience: 'İŞ DENEYİMİ',
        embedded_developer: 'Gömülü Yazılım Geliştirici',
        vestel_desc: 'Gömülü TV yazılımı üzerine çalışmaktayım.',
        fullstack_developer: 'Yazılım Geliştirici',
        ithero: 'IT HERO Bilgi Teknolojileri ve Tic.',
        ithero_desc: 'Autommate robotik süreç otomasyonu projesi üzerinde yazılım geliştirici olarak çalıştım.',
        rpa: 'Robotik Süreç Otomasyonu',
        see_project: 'Projeyi gör',
        technical_support: 'Teknik Destek',
        ts_desc: 'Uzaktan Eğitim Merkezi, Çanakkale Onsekiz Mart Üniversitesi bünyesinde kısmi zamanlı çalışan öğrenci.',
        ce_intern: 'Bilgisayar Mühendisliği Stajı',
        inc: 'A.Ş.',
        cei_desc: 'Eğitim teknolojileri, uygulama ve oyun geliştirme alanında staj.',
        achievements: 'Başarılar',
        tasks: 'Görevler',
        cashier: 'Kasiyer',
        sales_consultant: 'Satış Danışmanı',
        certificates: 'SERTİFİKALAR',
        airport_system: 'Havaalanı Rezervasyon Sistemi',
        credit_system: 'Kredi Sistemi',
        britishtown: 'BritishTown İngilizce C1 Seviyesi',
        bmo_docker: 'Bilgisayar Mühendisleri Odası Docker Eğitimi',
        coronathon: '21-22 Mart 2020 Coronathon Türkiye Etkinliği Başarılı Projeleri',
        occupational: 'İş Sağlığı ve Güvenliği Sertifikası',
        see_credential: 'Sertifikayı gör',
        final_project: 'Final Projesi',
        project: 'Proje'
    },
    en: {
        turkiye: 'Turkiye',
        skills: 'SKILLS',
        software_development: 'Software Development',
        interests: 'INTERESTS',
        fullstack_development: 'Full Stack Development',
        embedded_software: 'Embedded Software',
        mobile_development: 'Mobile Development',
        machine_learning: 'Machine Learning',
        image_processing: 'Image Processing',
        autonomous_system: 'Autonomous Systems',
        game_development: 'Game Development',
        languages: 'LANGUAGES',
        english: 'English',
        pwp: 'Professional Working Proficiency',
        turkish: 'Turkish',
        nbp: 'Native or Bilingual Proficiency',
        software_developer: 'Software Developer',
        prsnl_desc: 'The best adjective that describes me is curious. I always want to learn new things and search them to discover.',
        education: 'EDUCATION',
        computer_engineering: 'Computer Engineering',
        comu: 'Canakkale 18th March University',
        gpa: 'GPA',
        courses: 'Courses',
        read_more: 'read more',
        read_less: 'read less',
        less_courses: 'Mobile Programming, Image Processing, Computer Networks, Object Oriented Analysis And Design',
        more_courses: ', Algorithm and Programming, Linear Algebra, Structural Programming, Data Structures, Object Oriented Programming, Discrete Mathematics, Differantial Equations, Analog Electronics, Propbability and Statistics, Numerical Methods, Web Page Design and Programming, Computer Organization, Digital Elektronics, Database Management Systems, Managing Systems, Data Management and File Structures, Windows Programming, Micro Controllers, Data Mining, Programming Languages Concepts, Data Communication, Programmable Controllers, Microprocessors and Microcomputers, Software Engineering, Formal Languages and Automata Theory, Introduction to Cloud Computing, Computer Architecture, Analysis Of Algorithms, Embedded System Design, Access to the Internet of Things, Software Testing Techniques',
        uavproject: 'Unmanned Aerial Vehicle Project',
        management_i_s: 'Management Information Systems',
        anatolian_university: 'Anadolu University',
        present: 'Present',
        work_experience: 'WORK EXPERIENCE',
        embedded_developer: 'Embedded Software Engineer',
        vestel_desc: 'I\'m working on embedded TV software.',
        fullstack_developer: 'Full Stack Developer',
        ithero: 'IT HERO Information Technology & Services',
        ithero_desc: 'I worked on Autommate robotic process automation project as a full stack developer.',
        rpa: 'Robotic Process Automation',
        see_project: 'See project',
        technical_support: 'Technical Support',
        ts_desc: 'Part-time working student at Canakkale 18th March University Online Education Center.',
        ce_intern: 'Computer Engineering Internship',
        inc: 'Inc.',
        cei_desc: 'Educational technologies, application and game development.',
        achievements: 'Achievements',
        tasks: 'Tasks',
        cashier: 'Cashier',
        sales_consultant: 'Sales Consultant',
        certificates: 'CERTIFICATES',
        airport_system: 'Airport Reservation System',
        credit_system: 'Credit System',
        britishtown: 'BritishTown C1 Level in English',
        bmo_docker: 'The Chamber of Computer Engineers Docker Education',
        coronathon: '21-22 March 2020 Coronathon Turkey Activity Successful Projects',
        occupational: 'Occupational Health and Safety Certificate',
        see_credential: 'See credential',
        final_project: 'Final Project',
        project: 'Project'
    }
};