const lang_obj = {
    tr: {
        home: 'ANASAYFA',
        create: 'GÖNDERİ OLUŞTUR',
        login_register: 'GİRİŞ / KAYIT',
        profile_t: 'Profil',
        profile: 'PROFİL',
        admin_t: 'Yönetici',
        admin: 'YÖNETİCİ',
        sign_out_t: 'Çıkış',
        sign_out: 'ÇIKIŞ',
        welcome: 'HOŞGELDİNİZ!',
        html: 'HTML, CSS, JavaScript ve daha fazlasını, programlamayla ilgili her şeyi içeren haftalık blog makaleleri. Gönderileri kaçırmamak için bugün kaydolun!',
        view: 'GÖRÜNTÜLE',
        view_more: 'Son Gönderiler',
        never_miss: 'GÖNDERİLERİ KAÇIRMAYIN. ÜCRETSİZ KAYDOLUN!',
        register_blog: 'BLOGA KAYIT OL',
        posted: 'Tarih',
        account: 'Hesabınız yok mu?',
        register: 'Kaydol',
        login_blog: 'Blog\'a Giriş Yap',
        forgot: 'Parolanızı mı unuttunuz?',
        sign_in: 'OTURUM AÇ',
        login: 'Giriş Yap',
        already: 'Zaten hesabınız var mı?',
        create_account: 'Blog Hesabınızı Oluşturun',
        first_name_t: 'İsim',
        first_name: 'isim',
        last_name_t: 'Soy İsim',
        last_name: 'soy isim',
        username_t: 'Kullanıcı Adı',
        username: 'kullanıcı adı',
        email: 'e-posta',
        password: 'şifre',
        sign_up: 'ÜYE OL',
        back: 'Geri dön.',
        reset_password: 'Şifreyi Sıfırla',
        forgot_email: 'Parolanızı mı unuttunuz? Sıfırlamak için e-postanızı girin.',
        reset: 'Sıfırla',
        error: 'Hata:',
        ensure: 'Lütfen Blog Başlığı ve Gönderisinin doldurulduğundan emin olun.',
        ensure_cover: 'Lütfen bir kapak fotoğrafı yüklediğinizden emin olun.',
        saved: 'Değişiklikler kaydedildi.',
        title: 'Blog Başlığı Girin',
        upload: 'Kapak Fotoğrafı Yükle',
        preview_photo: 'Fotoğrafı Önizle',
        file: 'Seçilen Dosya',
        write: 'Blogunuzu buraya yazın...',
        publish: 'YAYINLA',
        preview: 'ÖNİZLE',
        save: 'DEĞİŞİKLİKLERİ KAYDET',
        toggle: 'Gönderi Düzenle',
        administration: 'Yönetim',
        add: 'Yönetici Ekle',
        enter: 'Yönetici yapmak için kullanıcı e-postasını girin',
        submit: 'GÖNDER',
        account_settings: 'Hesap Ayarları',
        copyright: 'Copyright 2023 Tüm Hakları Saklıdır',
    },
    en: {
        home: 'HOME',
        create: 'CREATE POST',
        login_register: 'LOGIN / REGISTER',
        profile_t: 'Profile',
        profile: 'PROFILE',
        admin_t: 'Admin',
        admin: 'ADMIN',
        sign_out_t: 'Sign Out',
        sign_out: 'SIGN OUT',
        welcome: 'WELCOME!',
        html: 'Weekly blog articles with all things programming including HTML, CSS, JavaScript and more. Register today to never miss a post!',
        view: 'VIEW THE POST',
        view_more: 'View More Recent Posts',
        never_miss: 'NEVER MISS A POST. REGISTER FOR YOUR FREE ACCOUNT TODAY!',
        register_blog: 'REGISTER FOR BLOG',
        posted: 'Posted on',
        account: 'Don\'t have an account?',
        register: 'Register',
        login_blog: 'Login to Blog',
        forgot: 'Forgot your password?',
        sign_in: 'SIGN IN',
        login: 'Login',
        already: 'Already have an account?',
        create_account: 'Create Your Blog Account',
        first_name_t: 'First Name',
        first_name: 'first name',
        last_name_t: 'Last Name',
        last_name: 'last name',
        username_t: 'Username',
        username: 'username',
        email: 'e-mail',
        password: 'password',
        sign_up: 'SIGN UP',
        back: 'Back to',
        reset_password: 'Reset Password',
        forgot_email: 'Forgot your password? Enter your email to reset it.',
        reset: 'Reset',
        error: 'Error:',
        ensure: 'Please ensure Blog Title & Blog Post has been filled.',
        ensure_cover: 'Please ensure you uploaded a cover photo.',
        saved: 'Changes Saved.',
        title: 'Enter Blog Title',
        upload: 'Upload Cover Photo',
        preview_photo: 'Preview Photo',
        file: 'File Chosen',
        write: 'Write your blog here...',
        publish: 'PUBLISH',
        preview: 'PREVIEW',
        save: 'SAVE CHANGES',
        toggle: 'Toggle Editing Post',
        administration: 'Administration',
        add: 'Add Admin',
        enter: 'Enter the user email to make them an admin',
        submit: 'SUBMIT',
        account_settings: 'Account Settings',
        copyright: 'Copyright 2023 All Rights Reserved',
    }
};