const lang_obj = {
    tr: {
        sentence: 'Cümle',
        word: 'Kelime',
        not_get_sentences:'Cümleler alınamadı.',
        not_get_words:'Kelimeler alınamadı.',
        found_sentences: 'Cümlelerde bulundu.',
        found_words: 'Kelimelerde bulundu.',
        not_found_sentences: 'Cümlelerde bulunamadı.',
        not_found_words: 'Kelimelerde bulunamadı.',
        find: 'Bul',
        image: 'resim',
        quote: 'alıntı',
        definition: 'tanım',
        type: 'tür',
        pos: 'Kelime Türü',
        result: 'Sonuç',
        clear: 'Temizle',
        copy: 'Kopyala',
        copied: 'Kopyalandı.',
    },
    en: {
        sentence: 'Sentence',
        word: 'Word',
        not_get_sentences:'Cannot get sentences.',
        not_get_words:'Cannot get words.',
        found_sentences: 'Found in sentences.',
        found_words: 'Found in words.',
        not_found_sentences: 'Not found in sentences.',
        not_found_words: 'Not found in words.',
        find: 'Find',
        image: 'image',
        quote: 'quote',
        definition: 'definition',
        type: 'type',
        pos: 'PoS (Part-of-Speech)',
        result: 'Result',
        clear: 'Clear',
        copy: 'Copy',
        copied: 'Copied.',
    }
}