const lang_obj = {
    tr: {
        privacy: 'Gizlilik Politikası',
        no_data: 'Veri Toplanmaz',
        extension: 'Eklenti:',
        overview: 'Genel Bakış',
        the_extension: '“Eklenti',
        by: '',
        cost: 'tarafından ücretsiz olarak sunulmaktadır ve olduğu gibi kullanılmak üzere tasarlanmıştır. Eklenti, arama sonuçlarını almak için YouTube API’sini kullanır',
        developer: 'Geliştirici:',
        your_privacy: 'Gizliliğinize saygı duyuyoruz. Bu Eklenti herhangi bir kişisel veya cihaz verisini',
        collect: 'toplamaz, saklamaz veya paylaşmaz.',
        any: '',
        accounts: 'Eklentide hesap, analiz, reklam SDK’sı, izleyici veya çerez gibi takip araçları yoktur',
        collection: 'Bilgi Toplama ve Kullanımı',
        request: 'Eklenti yalnızca YouTube API’sini kullanarak arama sonuçlarını elde eder. Cihazınızdan veya tarama etkinliğinizden geliştiriciye herhangi bir veri gönderilmez veya geliştirici tarafından saklanmaz. YouTube API istekleri yalnızca eklentinin temel işlevselliğini sağlamak amacıyla yapılır.',
        data: 'Veri Paylaşımı',
        share: 'Veri toplanmadığı için herhangi bir üçüncü taraf, hizmet sağlayıcı, reklamcı, bağlı ortaklık veya analiz platformu ile veri paylaşımı yapılmaz.',
        cookies: 'Çerez ve Takip',
        tracking: 'Eklenti çerez veya benzeri takip teknolojileri kullanmaz.',
        children: 'Çocukların Gizliliği',
        suitable: 'Eklenti her yaş grubuna uygundur. 13 yaş altındaki çocuklardan veya başka herhangi bir kullanıcıdan bilerek kişisel bilgi toplanmaz.',
        security: 'Güvenlik',
        secure: 'Eklenti kullanıcı verisi işlemediği için sunucularımızda korunması gereken kişisel veri bulunmamaktadır. Eklentinin orijinal ve güvenli sürümünü edinmek için yalnızca resmi eklenti mağazalarından indirmenizi öneririz.',
        changes: 'Politikadaki Değişiklikler',
        update: 'Eklenti veri toplamaya başlamaya karar verirse, bu politika değişiklikler yürürlüğe girmeden önce güncellenecektir.',
        last: 'Son güncelleme',
        date: 'tarihi yenilenecek ve gerektiğinde eklenti içinde ya da eklenti mağazası ilanında bildirim sağlanacaktır',
        contact: 'İletişim',
        about: 'Bu Gizlilik Politikası veya eklentinin gizlilik uygulamaları hakkında sorularınız varsa:',
        web: 'Web site:',
        effective: 'Yürürlük',
        june: 'Haziran',
        august: 'Ağustos',
        rights: 'Tüm hakları saklıdır'
    },
    en: {
        privacy: 'Privacy Policy',
        no_data: 'No Data Collected',
        extension: 'Extension:',
        overview: 'Overview',
        the_extension: 'the “Extension',
        by: 'is provided by',
        cost: 'at no cost and is intended to be used as is. The Extension uses the YouTube API to retrieve search results',
        developer: 'Developer:',
        your_privacy: 'We respect your privacy. This Extension does',
        collect: 'not collect, store, or share',
        any: 'any personal or device data.',
        accounts: 'There are no accounts, analytics, advertising SDKs, trackers, or cookies',
        collection: 'Information Collection and Use',
        request: 'The Extension only uses the YouTube API to obtain search results. No data from your device or browsing activity is transmitted to the developer or stored by the developer. Any requests to the YouTube API are for the sole purpose of providing the Extension’s core functionality.',
        data: 'Data Sharing',
        share: 'Because we do not collect data, we do not share any data with third parties, service providers, advertisers, affiliates, or analytics platforms.',
        cookies: 'Cookies and Tracking',
        tracking: 'The Extension does not use cookies or similar tracking technologies.',
        children: 'Children’s Privacy',
        suitable: 'The Extension is suitable for users of all ages. We do not knowingly collect personal information from children under 13, or from any user.',
        security: 'Security',
        secure: 'Since the Extension does not handle user data, there is no personal information stored on our servers that requires protection. To ensure authenticity and integrity, download the Extension only from official extension stores where we publish it.',
        changes: 'Changes to This Policy',
        update: 'If the Extension changes to begin collecting data, this policy will be updated before such changes take effect. We will revise the',
        last: 'Last updated',
        date: 'date below and, where required, provide notice within the Extension or via the extension store listing',
        contact: 'Contact Us',
        about: 'If you have questions about this Privacy Policy or the Extension’s practices, contact:',
        web: 'Website:',
        effective: 'Effective',
        june: 'June',
        august: 'August',
        rights: 'All rights reserved'
    }
};